version: '3.3'
services:
    renew:
        restart: always
        volumes:
            - './Deploy:/renewx/Deploy'
            - 'appdata:/renewx/appdata'
        ports:
            - '127.0.0.1:1066:1066'
        container_name: renew
        image: 'gladtbam/ms365_e5_renewx:latest'
    backup:
        image: alpine
        volumes:
          - appdata:/backup-volume
          - ./backup:/backup
        command: tar cavf /backup/data-backup.tar.gz -C /backup-volume .
        profiles: ["backup"]
    restore:
        image: alpine
        volumes:
          - appdata:/backup-volume
          - ./backup:/backup
        command: tar xaf /backup/data-backup.tar.gz -C /backup-volume .
        profiles: ["restore"]
volumes:
    appdata:

